use crate::bytecode::{SecurityFinding, SecuritySeverity};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerbatimYulInjectionVulnerability {
    pub location: usize,
    pub severity: String,
    pub description: String,
    pub confidence: f32,
}

/// Solidity Verbatim Yul Injection Detector
///
/// Detects security vulnerabilities related to Solidity's `verbatim` builtin in inline assembly,
/// which allows inserting raw bytecode without validation. This can introduce critical vulnerabilities
/// if misused or if the surrounding optimizer context changes behavior.
///
/// CVE Context: Verbatim blocks bypass Solidity's safety checks
/// Impact: Complete security model bypass, arbitrary code execution
/// Affected: Any Solidity version supporting inline assembly with verbatim
///
/// Real-World Risks:
/// - Raw opcode injection can bypass access control
/// - Optimizer may reorder code around verbatim blocks incorrectly
/// - Stack manipulation can corrupt nearby variables
/// - Invalid opcodes can cause unexpected reverts
/// - SELFDESTRUCT in verbatim blocks bypasses deprecation warnings
///
/// Detection Strategy:
/// - Identifies unusual opcode sequences characteristic of manual injection
/// - Detects raw bytecode patterns not generated by Solidity compiler
/// - Looks for dangerous opcodes (SELFDESTRUCT, DELEGATECALL) in suspicious contexts
/// - Checks for stack manipulation that suggests verbatim usage
/// - Identifies optimizer-incompatible bytecode patterns
pub struct SolidityVerbatimYulInjectionDetector;

impl SolidityVerbatimYulInjectionDetector {
    pub fn new() -> Self {
        Self
    }

    pub fn detect(&self, bytecode: &[u8]) -> Vec<SecurityFinding> {
        let mut findings = Vec::new();
        let mut i = 0;

        while i < bytecode.len() {
            // Pattern 1: Raw SELFDESTRUCT in unusual context (verbatim abuse)
            if bytecode[i] == 0xff {
                if self.has_verbatim_selfdestruct_pattern(bytecode, i) {
                    findings.push(SecurityFinding {
                        severity: SecuritySeverity::Critical,
                        description: "Verbatim Yul injection: Raw SELFDESTRUCT in unusual context suggests verbatim block bypassing safety checks".to_string(),
                        pc: i,
                        confidence: 0.89,
                    });
                }
            }

            // Pattern 2: Unusual DELEGATECALL without standard proxy pattern
            if bytecode[i] == 0xf4 {
                if self.has_raw_delegatecall_injection(bytecode, i) {
                    findings.push(SecurityFinding {
                        severity: SecuritySeverity::Critical,
                        description: "Verbatim Yul DELEGATECALL: Raw delegatecall without standard checks suggests inline assembly injection".to_string(),
                        pc: i,
                        confidence: 0.87,
                    });
                }
            }

            // Pattern 3: Manual stack manipulation suggesting verbatim usage
            if self.is_dup_opcode(bytecode[i]) {
                if self.has_verbatim_stack_manipulation(bytecode, i) {
                    findings.push(SecurityFinding {
                        severity: SecuritySeverity::High,
                        description: "Verbatim stack manipulation: Unusual DUP/SWAP patterns suggest raw bytecode injection via verbatim".to_string(),
                        pc: i,
                        confidence: 0.85,
                    });
                }
            }

            // Pattern 4: Invalid or deprecated opcodes
            if self.is_invalid_or_deprecated_opcode(bytecode[i]) {
                findings.push(SecurityFinding {
                    severity: SecuritySeverity::High,
                    description: "Invalid/deprecated opcode detected: Likely injected via verbatim Yul block, may cause unexpected behavior".to_string(),
                    pc: i,
                    confidence: 0.86,
                });
            }

            // Pattern 5: Raw CREATE2 with manual salt calculation (verbatim pattern)
            if bytecode[i] == 0xf5 {
                if self.has_verbatim_create2_pattern(bytecode, i) {
                    findings.push(SecurityFinding {
                        severity: SecuritySeverity::High,
                        description: "Verbatim CREATE2: Manual CREATE2 implementation suggests inline assembly injection with security risks".to_string(),
                        pc: i,
                        confidence: 0.84,
                    });
                }
            }

            // Pattern 6: Optimizer-incompatible bytecode sequence
            if bytecode[i] == 0x5b {
                if self.has_optimizer_incompatible_pattern(bytecode, i) {
                    findings.push(SecurityFinding {
                        severity: SecuritySeverity::Medium,
                        description: "Optimizer-incompatible pattern: Bytecode sequence suggests verbatim block that may break with optimizer changes".to_string(),
                        pc: i,
                        confidence: 0.82,
                    });
                }
            }

            i += 1;
        }

        findings
    }

    pub fn detect_vulnerabilities(&self, bytecode: &[u8]) -> Vec<VerbatimYulInjectionVulnerability> {
        self.detect(bytecode)
            .into_iter()
            .map(|finding| VerbatimYulInjectionVulnerability {
                location: finding.pc,
                severity: format!("{:?}", finding.severity),
                description: finding.description,
                confidence: finding.confidence as f32,
            })
            .collect()
    }

    fn has_verbatim_selfdestruct_pattern(&self, bytecode: &[u8], pos: usize) -> bool {
        let lookback = 15.min(pos);
        let mut has_minimal_checks = true;
        let mut has_jumpi = false;
        let mut has_caller_check = false;

        // Standard Solidity SELFDESTRUCT has access control checks
        for offset in 1..=lookback {
            if pos >= offset {
                match bytecode[pos - offset] {
                    0x57 => has_jumpi = true, // JUMPI (conditional)
                    0x33 => has_caller_check = true, // CALLER
                    0x14 => has_caller_check = true, // EQ (comparison)
                    _ => {}
                }
            }
        }

        // Verbatim SELFDESTRUCT lacks standard safety checks
        if has_jumpi && has_caller_check {
            has_minimal_checks = false;
        }

        has_minimal_checks
    }

    fn has_raw_delegatecall_injection(&self, bytecode: &[u8], pos: usize) -> bool {
        let lookback = 20.min(pos);
        let mut has_returndatasize = false;
        let mut has_standard_pattern = false;
        let mut push_count = 0;

        // Standard proxy patterns use specific sequences
        for offset in 1..=lookback {
            if pos >= offset {
                match bytecode[pos - offset] {
                    0x3d => has_returndatasize = true, // RETURNDATASIZE
                    0x36 => has_standard_pattern = true, // CALLDATASIZE
                    0x60..=0x7f => push_count += 1, // PUSH operations
                    _ => {}
                }
            }
        }

        // Raw DELEGATECALL without standard proxy pattern
        !has_returndatasize && !has_standard_pattern && push_count < 3
    }

    fn has_verbatim_stack_manipulation(&self, bytecode: &[u8], pos: usize) -> bool {
        let window = 12.min(bytecode.len().saturating_sub(pos));
        let mut dup_count = 1; // Current DUP
        let mut swap_count = 0;
        let mut operations_between = 0;

        for offset in 1..window {
            if pos + offset < bytecode.len() {
                match bytecode[pos + offset] {
                    0x80..=0x8f => dup_count += 1, // DUP1-DUP16
                    0x90..=0x9f => swap_count += 1, // SWAP1-SWAP16
                    _ => operations_between += 1,
                }
            }
        }

        // Unusual stack patterns: many DUP/SWAP with few other operations
        dup_count >= 4 && swap_count >= 3 && operations_between < 5
    }

    fn is_invalid_or_deprecated_opcode(&self, opcode: u8) -> bool {
        match opcode {
            0x0c..=0x0f => true, // Undefined arithmetic opcodes
            0x1e | 0x1f => true, // Undefined comparison opcodes
            0x21..=0x2f => true, // Undefined crypto opcodes
            0x49..=0x4f => true, // Undefined block opcodes
            0xa5..=0xef => true, // Undefined opcodes
            0xf6..=0xf9 => true, // Undefined call opcodes
            0xfb | 0xfc => true, // Undefined opcodes
            0xfe => true, // INVALID opcode (unless intentional)
            _ => false,
        }
    }

    fn has_verbatim_create2_pattern(&self, bytecode: &[u8], pos: usize) -> bool {
        let lookback = 25.min(pos);
        let mut has_salt_calc = false;
        let mut has_keccak = false;
        let mut has_manual_memory = false;
        let mut push_count = 0;

        // Manual CREATE2 with salt calculation
        for offset in 1..=lookback {
            if pos >= offset {
                match bytecode[pos - offset] {
                    0x20 => has_keccak = true, // KECCAK256 (for salt)
                    0x52 => has_manual_memory = true, // MSTORE
                    0x02 | 0x01 => has_salt_calc = true, // MUL or ADD
                    0x60..=0x7f => push_count += 1, // PUSH operations
                    _ => {}
                }
            }
        }

        // Verbatim CREATE2 has manual salt calculation
        has_keccak && has_salt_calc && has_manual_memory && push_count >= 3
    }

    fn has_optimizer_incompatible_pattern(&self, bytecode: &[u8], pos: usize) -> bool {
        let window = 15.min(bytecode.len().saturating_sub(pos));
        let mut jumpdest_count = 1; // Current JUMPDEST
        let mut operation_count = 0;
        let mut has_jump = false;

        // Pattern: Multiple JUMPDESTs with minimal operations (optimizer would remove)
        for offset in 1..window {
            if pos + offset < bytecode.len() {
                match bytecode[pos + offset] {
                    0x5b => jumpdest_count += 1, // JUMPDEST
                    0x56 | 0x57 => has_jump = true, // JUMP or JUMPI
                    _ => operation_count += 1,
                }
            }
        }

        // Multiple consecutive JUMPDESTs suggest verbatim code
        jumpdest_count >= 3 && operation_count < 5 && !has_jump
    }

    fn is_dup_opcode(&self, opcode: u8) -> bool {
        matches!(opcode, 0x80..=0x8f) // DUP1-DUP16
    }
}
