use crate::bytecode::{SecurityFinding, SecuritySeverity};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OptimizerYulBugVulnerability {
    pub location: usize,
    pub severity: String,
    pub description: String,
    pub confidence: f32,
}

/// Solidity Optimizer Yul Bug Detector
///
/// Detects vulnerabilities related to the Solidity optimizer's Yul IR code generation bugs
/// that can lead to incorrect bytecode and unexpected behavior.
///
/// Known Issues:
/// - FullInliner bug (versions 0.6.0-0.8.15): Incorrect inlining of functions
/// - Yul optimizer sequence bug: Incorrect optimization of JUMPDEST removal
/// - Memory management bug: Incorrect stack-to-memory variable moves
/// - Expression simplifier bug: Incorrect constant folding
///
/// Real-World Impact:
/// - Incorrect state transitions in complex contracts
/// - Logic bypasses in access control
/// - Fund loss due to incorrect arithmetic
///
/// Detection Strategy:
/// - Identifies aggressive optimizer patterns (JUMP sequences, inlining)
/// - Detects suspicious constant folding results
/// - Looks for unusual stack manipulation patterns
/// - Checks for optimizer-generated dead code
pub struct SolidityOptimizerYulBugDetector;

impl SolidityOptimizerYulBugDetector {
    pub fn new() -> Self {
        Self
    }

    pub fn detect(&self, bytecode: &[u8]) -> Vec<SecurityFinding> {
        let mut findings = Vec::new();
        let mut i = 0;

        while i < bytecode.len() {
            // Pattern 1: FullInliner bug - suspicious function inlining
            // JUMP (0x56) immediately followed by JUMPDEST (0x5b) with minimal operations
            if bytecode[i] == 0x56 {
                if self.has_fullinliner_bug_pattern(bytecode, i) {
                    findings.push(SecurityFinding {
                        severity: SecuritySeverity::Critical,
                        description: "Solidity FullInliner optimizer bug: Aggressive function inlining may cause incorrect control flow (0.6.0-0.8.15)".to_string(),
                        pc: i,
                        confidence: 0.87,
                    });
                }
            }

            // Pattern 2: Yul optimizer sequence bug - incorrect JUMPDEST handling
            // Multiple JUMPDEST operations in sequence with unusual spacing
            if bytecode[i] == 0x5b {
                if self.has_jumpdest_removal_bug(bytecode, i) {
                    findings.push(SecurityFinding {
                        severity: SecuritySeverity::High,
                        description: "Yul optimizer JUMPDEST removal bug: Control flow may be incorrectly optimized leading to logic bypass".to_string(),
                        pc: i,
                        confidence: 0.85,
                    });
                }
            }

            // Pattern 3: Memory management bug - incorrect stack-to-memory moves
            // MSTORE (0x52) with DUP operations that suggest incorrect optimization
            if bytecode[i] == 0x52 {
                if self.has_memory_management_bug(bytecode, i) {
                    findings.push(SecurityFinding {
                        severity: SecuritySeverity::High,
                        description: "Yul optimizer memory management bug: Stack-to-memory variable moves may be incorrectly optimized".to_string(),
                        pc: i,
                        confidence: 0.84,
                    });
                }
            }

            // Pattern 4: Expression simplifier bug - incorrect constant folding
            // Arithmetic operations with constants that should be optimized but aren't
            if self.is_arithmetic_opcode(bytecode[i]) {
                if self.has_constant_folding_bug(bytecode, i) {
                    findings.push(SecurityFinding {
                        severity: SecuritySeverity::Medium,
                        description: "Yul expression simplifier bug: Constant folding may produce incorrect results in edge cases".to_string(),
                        pc: i,
                        confidence: 0.82,
                    });
                }
            }

            // Pattern 5: Dead code generated by optimizer
            // Unreachable code after unconditional operations
            if bytecode[i] == 0xfe || bytecode[i] == 0x00 {
                if self.has_optimizer_dead_code(bytecode, i) {
                    findings.push(SecurityFinding {
                        severity: SecuritySeverity::Medium,
                        description: "Optimizer-generated dead code detected: May indicate optimizer bug or unexpected control flow".to_string(),
                        pc: i,
                        confidence: 0.80,
                    });
                }
            }

            i += 1;
        }

        findings
    }

    pub fn detect_vulnerabilities(&self, bytecode: &[u8]) -> Vec<OptimizerYulBugVulnerability> {
        self.detect(bytecode)
            .into_iter()
            .map(|finding| OptimizerYulBugVulnerability {
                location: finding.pc,
                severity: format!("{:?}", finding.severity),
                description: finding.description,
                confidence: finding.confidence as f32,
            })
            .collect()
    }

    fn has_fullinliner_bug_pattern(&self, bytecode: &[u8], pos: usize) -> bool {
        let window = 15.min(bytecode.len().saturating_sub(pos));
        let mut jumpdest_nearby = false;
        let mut operations_between = 0;
        let mut has_return = false;

        for offset in 1..window {
            if pos + offset < bytecode.len() {
                match bytecode[pos + offset] {
                    0x5b => {
                        jumpdest_nearby = true;
                        break;
                    }
                    0xf3 | 0xfd => has_return = true,
                    _ => operations_between += 1,
                }
            }
        }

        // FullInliner bug: JUMP immediately followed by JUMPDEST with minimal ops
        jumpdest_nearby && operations_between < 3 && !has_return
    }

    fn has_jumpdest_removal_bug(&self, bytecode: &[u8], pos: usize) -> bool {
        let window = 20.min(bytecode.len().saturating_sub(pos));
        let mut jumpdest_count = 1; // Current JUMPDEST
        let mut operations_count = 0;
        let mut has_jump = false;

        for offset in 1..window {
            if pos + offset < bytecode.len() {
                match bytecode[pos + offset] {
                    0x5b => jumpdest_count += 1,
                    0x56 | 0x57 => has_jump = true,
                    _ => operations_count += 1,
                }
            }
        }

        // Multiple JUMPDESTs with minimal operations suggests incorrect optimization
        jumpdest_count >= 3 && operations_count < 10 && has_jump
    }

    fn has_memory_management_bug(&self, bytecode: &[u8], pos: usize) -> bool {
        let lookback = 10.min(pos);
        let mut dup_count = 0;
        let mut swap_count = 0;
        let mut has_mload = false;

        for offset in 1..=lookback {
            if pos >= offset {
                match bytecode[pos - offset] {
                    0x80..=0x8f => dup_count += 1, // DUP1-DUP16
                    0x90..=0x9f => swap_count += 1, // SWAP1-SWAP16
                    0x51 => has_mload = true, // MLOAD
                    _ => {}
                }
            }
        }

        // Excessive DUP/SWAP operations before MSTORE suggest memory management issues
        dup_count >= 3 && swap_count >= 2 && has_mload
    }

    fn has_constant_folding_bug(&self, bytecode: &[u8], pos: usize) -> bool {
        let lookback = 8.min(pos);
        let window = 8.min(bytecode.len().saturating_sub(pos));
        let mut has_push_before = false;
        let mut has_push_after = false;
        let mut push_count = 0;

        // Check for constants before and after arithmetic
        for offset in 1..=lookback {
            if pos >= offset && self.is_push_opcode(bytecode[pos - offset]) {
                has_push_before = true;
                push_count += 1;
            }
        }

        for offset in 1..window {
            if pos + offset < bytecode.len() && self.is_push_opcode(bytecode[pos + offset]) {
                has_push_after = true;
                push_count += 1;
            }
        }

        // Multiple constants with arithmetic should be folded
        has_push_before && has_push_after && push_count >= 2
    }

    fn has_optimizer_dead_code(&self, bytecode: &[u8], pos: usize) -> bool {
        let window = 25.min(bytecode.len().saturating_sub(pos));
        let mut has_operations = false;
        let mut operation_count = 0;

        for offset in 1..window {
            if pos + offset < bytecode.len() {
                if bytecode[pos + offset] != 0x00 && bytecode[pos + offset] != 0xfe {
                    has_operations = true;
                    operation_count += 1;
                }
            }
        }

        // Dead code after INVALID/STOP with multiple operations
        has_operations && operation_count >= 5
    }

    fn is_arithmetic_opcode(&self, opcode: u8) -> bool {
        matches!(opcode, 0x01..=0x05 | 0x08..=0x0b) // ADD, MUL, SUB, DIV, MOD, ADDMOD, MULMOD, EXP
    }

    fn is_push_opcode(&self, opcode: u8) -> bool {
        matches!(opcode, 0x60..=0x7f) // PUSH1-PUSH32
    }
}
