#!/bin/bash
# Remove remaining non-existent validator calls - Batch 3 (final)

FILE="src/analysis/comprehensive_analyzer.rs"

sed -i '' 's/ && validator\.validate_rfq(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_rollup_boost(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_rpc_mev(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_scroll_l1_gateway(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_seaport(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_searcher_collusion(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_secp256r1(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_securities_law(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_selfish_mining(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_seneca(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_sense(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_session_key(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_settlement_layer(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_shido(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_slot_auction(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_social_graph(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_social_recovery(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_social_token(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_socket_gateway(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_solver_competition(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_soul_wallet(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_soulbound_token(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_sovereign_rollup(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_sqrt_price(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_sqrt_rounding(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_ssv_network(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_stableswap(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_starknet(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_storage_proof(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_sui_move(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_swell(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_symbiotic(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_tee_attestation(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_threshold_signature(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_time_bandit(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_timelock_bypass(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_token_streaming(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_toxic_orderflow(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_trader_joe(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_tragedy_of_commons(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_transient_storage_reentrancy(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_twap_manipulation(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_two_step_ownership(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_uncle_bandit(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_uniswap_v4_hooks(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_uniswap_v4_singleton(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_validator_mev(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_vampire_attack(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_vault_strategy(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_ve_token(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_verkle_proof(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_vote_buying(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_woofi(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_yield_aggregator(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_yield_tokenization(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_zerodev(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_zk_circuit(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_zk_coprocessor(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_zk_email(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_zkevm_compatibility(v\.location)//' "$FILE"
sed -i '' 's/ && validator\.validate_aave_liquidation(v\.location)//' "$FILE"

echo "Batch 3 complete (all non-existent validators removed!)"
echo "Now trying to build..."
