// English Contract Translation Demo
// Shows the complete pipeline: English → Rust → WASM → Verified

use anyhow::Result;
use verify::english::*;

#[tokio::main]
async fn main() -> Result<()> {
    println!("🚀 Aristo English Contract Translation Demo\n");
    println!("=" .repeat(60));
    
    // Example English contract
    let contract = create_example_token_contract();
    
    println!("\n📝 ENGLISH CONTRACT SPECIFICATION:");
    println!("Name: {}", contract.name);
    println!("Description: {}", contract.description);
    println!("Functions: {}", contract.functions.len());
    
    for (i, func) in contract.functions.iter().enumerate() {
        println!("  {}. {} (", i + 1, func.name);
        for param in &func.parameters {
            println!("       {}: {}", param.name, param.param_type);
        }
        println!("  )");
    }
    
    println!("\n" + &"=".repeat(60));
    println!("\n⚙️  TRANSLATION PIPELINE:\n");
    
    // Initialize pipeline
    println!("1️⃣  Initializing pipeline...");
    let pipeline = match EnglishContractPipeline::new() {
        Ok(p) => {
            println!("   ✅ Pipeline ready");
            p
        }
        Err(e) => {
            println!("   ❌ Failed: {}", e);
            println!("\n💡 TIP: Set ANTHROPIC_API_KEY environment variable");
            println!("   export ANTHROPIC_API_KEY=your_key_here");
            return Err(e);
        }
    };
    
    // Validate English contract
    println!("\n2️⃣  Validating English contract...");
    let validation = pipeline.validator.validate(&contract)?;
    println!("   ✅ Validation passed");
    if !validation.warnings.is_empty() {
        println!("   ⚠️  Warnings:");
        for warning in &validation.warnings {
            println!("       - {}", warning);
        }
    }
    
    // Translate to Rust
    println!("\n3️⃣  Translating to Rust code (using AI)...");
    println!("   🤖 Calling Claude API...");
    
    let rust_code = match pipeline.translator.translate_to_rust(&contract).await {
        Ok(code) => {
            println!("   ✅ Translation complete ({} bytes)", code.len());
            code
        }
        Err(e) => {
            println!("   ❌ Translation failed: {}", e);
            return Err(e);
        }
    };
    
    println!("\n   📄 Generated Rust code preview:");
    println!("   {}", "-".repeat(58));
    for (i, line) in rust_code.lines().take(15).enumerate() {
        println!("   {:3} | {}", i + 1, line);
    }
    if rust_code.lines().count() > 15 {
        println!("   ... ({} more lines)", rust_code.lines().count() - 15);
    }
    println!("   {}", "-".repeat(58));
    
    // Compile to WASM
    println!("\n4️⃣  Compiling Rust to WASM...");
    let wasm_bytes = match pipeline.compile_rust_to_wasm(&rust_code) {
        Ok(bytes) => {
            println!("   ✅ Compilation successful ({} bytes)", bytes.len());
            bytes
        }
        Err(e) => {
            println!("   ❌ Compilation failed: {}", e);
            println!("\n   Generated Rust code:");
            println!("   {}", rust_code);
            return Err(e);
        }
    };
    
    // Verify WASM
    println!("\n5️⃣  Verifying WASM with formal verification...");
    match verify::verify_wasm(&wasm_bytes) {
        Ok(_) => {
            println!("   ✅ WASM validation passed");
        }
        Err(e) => {
            println!("   ❌ Verification failed: {}", e);
            return Err(e);
        }
    }
    
    println!("\n" + &"=".repeat(60));
    println!("\n✅ SUCCESS! Complete pipeline executed:");
    println!("   • English contract validated");
    println!("   • Rust code generated by AI");
    println!("   • WASM bytecode compiled");
    println!("   • Safety properties verified");
    println!("\n📦 Contract ready for deployment!");
    println!("\n" + &"=".repeat(60));
    
    Ok(())
}

fn create_example_token_contract() -> EnglishContract {
    use std::collections::HashMap;
    
    EnglishContract {
        name: "SimpleToken".to_string(),
        description: "A basic fungible token with transfer functionality".to_string(),
        config: HashMap::from([
            ("total_supply".to_string(), "1000000".to_string()),
            ("decimals".to_string(), "18".to_string()),
        ]),
        state: vec![
            StateVariable {
                name: "balances".to_string(),
                var_type: "HashMap<Address, u64>".to_string(),
                description: "Token balances for each address".to_string(),
                initial_value: None,
            },
            StateVariable {
                name: "total_supply".to_string(),
                var_type: "u64".to_string(),
                description: "Total token supply".to_string(),
                initial_value: Some("1000000".to_string()),
            },
        ],
        functions: vec![
            ContractFunction {
                name: "transfer".to_string(),
                description: "Transfer tokens to another address".to_string(),
                parameters: vec![
                    Parameter {
                        name: "to".to_string(),
                        param_type: "Address".to_string(),
                        description: "Recipient address".to_string(),
                    },
                    Parameter {
                        name: "amount".to_string(),
                        param_type: "u64".to_string(),
                        description: "Amount to transfer".to_string(),
                    },
                ],
                returns: vec![
                    ReturnType {
                        return_type: "bool".to_string(),
                        description: "Success status".to_string(),
                    },
                ],
                requirements: vec![
                    "Sender must have at least {amount} tokens in balance".to_string(),
                    "Recipient address cannot be zero".to_string(),
                    "Amount must be greater than zero".to_string(),
                ],
                steps: vec![
                    "Validate parameters (bounds check: max 1024 bytes)".to_string(),
                    "Get sender address from context".to_string(),
                    "Check sender has sufficient balance".to_string(),
                    "Subtract {amount} from sender's balance".to_string(),
                    "Add {amount} to recipient's balance".to_string(),
                    "Emit Transfer event".to_string(),
                    "Return true for success".to_string(),
                ],
                visibility: Visibility::Public,
            },
            ContractFunction {
                name: "balance_of".to_string(),
                description: "Get token balance of an address".to_string(),
                parameters: vec![
                    Parameter {
                        name: "account".to_string(),
                        param_type: "Address".to_string(),
                        description: "Address to check balance".to_string(),
                    },
                ],
                returns: vec![
                    ReturnType {
                        return_type: "u64".to_string(),
                        description: "Token balance".to_string(),
                    },
                ],
                requirements: vec![],
                steps: vec![
                    "Look up balance in balances mapping".to_string(),
                    "Return balance (or 0 if not found)".to_string(),
                ],
                visibility: Visibility::Public,
            },
        ],
        events: vec![
            ContractEvent {
                name: "Transfer".to_string(),
                parameters: vec![
                    Parameter {
                        name: "from".to_string(),
                        param_type: "Address".to_string(),
                        description: "Sender".to_string(),
                    },
                    Parameter {
                        name: "to".to_string(),
                        param_type: "Address".to_string(),
                        description: "Recipient".to_string(),
                    },
                    Parameter {
                        name: "amount".to_string(),
                        param_type: "u64".to_string(),
                        description: "Amount".to_string(),
                    },
                ],
            },
        ],
    }
}
