/**
 * Trustless SDK - Core Types
 * 
 * Defines the public API types for the Trustless SDK
 */

import type { TransactionRequest, TransactionResponse } from 'ethers';

// ============================================================================
// Transaction Types
// ============================================================================

/**
 * A transaction to be proven and executed trustlessly
 */
export interface TrustlessTransaction extends TransactionRequest {
  to: string;
  data?: string;
  value?: bigint | string;
  gasLimit?: bigint | string;
}

/**
 * Multiple transactions to be executed atomically
 */
export interface AtomicBundle {
  transactions: TrustlessTransaction[];
  revertOnFailure?: boolean;
  maxGasPerTransaction?: bigint;
}

// ============================================================================
// Proof Types
// ============================================================================

/**
 * ZK Proof generated by ZODA
 */
export interface ZKProof {
  proof: Uint8Array;
  publicInputs: Uint8Array;
  proofHash: string;
  provingTime: number; // milliseconds
}

/**
 * Security verification result from PCC analysis
 */
export interface SecurityVerification {
  isSecure: boolean;
  vulnerabilities: Vulnerability[];
  securityScore: number; // 0-100
  pccProofHash: string;
}

/**
 * Detected vulnerability
 */
export interface Vulnerability {
  type: VulnerabilityType;
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  description: string;
  location?: string;
  remediation?: string;
}

export type VulnerabilityType =
  | 'REENTRANCY'
  | 'INTEGER_OVERFLOW'
  | 'UNCHECKED_CALL'
  | 'DELEGATECALL'
  | 'TIMESTAMP_DEPENDENCY'
  | 'TX_ORIGIN'
  | 'SELFDESTRUCT'
  | 'MEV_VULNERABLE'
  | 'FLASH_LOAN_ATTACK'
  | 'ORACLE_MANIPULATION'
  | 'ACCESS_CONTROL'
  | 'OTHER';

/**
 * Complete trustless proof containing both ZK proof and security verification
 */
export interface TrustlessProof {
  zkProof: ZKProof;
  security: SecurityVerification;
  transaction: TrustlessTransaction;
  timestamp: number;
  trustlessScore: number; // 0-100, composite score
}

/**
 * Atomic execution proof for transaction bundles
 */
export interface AtomicProof {
  proofs: TrustlessProof[];
  bundleHash: string;
  guaranteedAtomic: boolean;
  totalGasEstimate: bigint;
}

// ============================================================================
// Result Types
// ============================================================================

/**
 * Result of proving a transaction
 */
export interface ProvingResult {
  success: boolean;
  proof?: TrustlessProof;
  error?: Error;
  metrics: ProvingMetrics;
}

/**
 * Performance metrics for proving
 */
export interface ProvingMetrics {
  provingTime: number; // ms
  securityAnalysisTime: number; // ms
  totalTime: number; // ms
  proofSize: number; // bytes
  transactionSize: number; // bytes
  compressionRatio: number;
}

/**
 * Result of submitting a trustless transaction
 */
export interface SubmitResult {
  success: boolean;
  transactionHash?: string;
  receipt?: TransactionResponse;
  error?: Error;
}

// ============================================================================
// Configuration Types
// ============================================================================

/**
 * SDK configuration options
 */
export interface TrustlessConfig {
  /** Network to connect to */
  network?: 'mainnet' | 'goerli' | 'sepolia' | 'localhost' | string;
  
  /** RPC endpoint URL */
  rpcUrl?: string;
  
  /** Enable security verification (PCC) */
  enableSecurity?: boolean;
  
  /** Security analysis strictness level */
  securityLevel?: 'BASIC' | 'STANDARD' | 'STRICT' | 'PARANOID';
  
  /** Enable automatic WARP proof compression */
  enableCompression?: boolean;
  
  /** Proving timeout in milliseconds */
  provingTimeout?: number;
  
  /** Enable detailed logging */
  debug?: boolean;
  
  /** Custom verifier contract address */
  verifierContract?: string;
  
  /** Custom atomic executor contract address */
  atomicExecutorContract?: string;
  
  /** Proving server URL (hosted or localhost) */
  provingServer?: string;
  
  /** Fallback to WASM if server unavailable */
  fallbackToWasm?: boolean;
  
  /** Payment configuration for FRAC tokens */
  payment?: PaymentConfig;
}

// ============================================================================
// Payment Types
// ============================================================================

/**
 * Payment configuration for using FRAC tokens
 */
export interface PaymentConfig {
  /** Enable FRAC payment (default: false for free testnet mode) */
  enabled: boolean;
  
  /** FRAC token contract address */
  fracTokenAddress?: string;
  
  /** Reward pool contract address */
  rewardPoolAddress?: string;
  
  /** User's wallet private key or signer */
  payerKey?: string;
  
  /** Max FRAC willing to pay per proof (in wei) */
  maxPricePerProof?: bigint;
  
  /** Auto-approve spending (requires approval tx first) */
  autoApprove?: boolean;
}

/**
 * Payment receipt after proof generation
 */
export interface PaymentReceipt {
  /** Transaction hash of payment */
  txHash: string;
  
  /** Amount paid in FRAC (wei) */
  amountPaid: bigint;
  
  /** Prover address that received payment */
  proverAddress: string;
  
  /** Block number of payment */
  blockNumber: number;
  
  /** Timestamp of payment */
  timestamp: number;
}

/**
 * Proof result with payment info
 */
export interface TrustlessProofWithPayment extends TrustlessProof {
  payment?: PaymentReceipt;
}

/**
 * SDK initialization status
 */
export interface InitStatus {
  initialized: boolean;
  wasmLoaded: boolean;
  network: string;
  blockNumber?: number;
  error?: Error;
}

// ============================================================================
// Event Types
// ============================================================================

/**
 * Events emitted during proving
 */
export type ProvingEvent =
  | { type: 'STARTED'; transaction: TrustlessTransaction }
  | { type: 'SECURITY_ANALYSIS'; progress: number }
  | { type: 'PROOF_GENERATION'; progress: number }
  | { type: 'COMPRESSION'; progress: number }
  | { type: 'COMPLETED'; proof: TrustlessProof }
  | { type: 'ERROR'; error: Error };

/**
 * Callback for proving events
 */
export type ProvingCallback = (event: ProvingEvent) => void;

// ============================================================================
// Statistics Types
// ============================================================================

/**
 * Overall SDK statistics
 */
export interface TrustlessStats {
  totalProofs: number;
  successfulProofs: number;
  failedProofs: number;
  averageProvingTime: number;
  averageProofSize: number;
  totalGasSaved: bigint;
  vulnerabilitiesDetected: number;
  trustlessScore: number; // average across all proofs
}

// ============================================================================
// Export Collections
// ============================================================================

export type { TransactionRequest, TransactionResponse } from 'ethers';
