use crate::block_execution::{TransactionProcessor, TransactionResult, BlockExecutionConfig};
use ethereum_types::{H256, U256};
use std::time::Duration;
use tokio::test;

#[tokio::test]
async fn test_zoda_batch_proof_generation() {
    // Create processor with default configuration
    let config = BlockExecutionConfig::default();
    let processor = TransactionProcessor::new(config).await.expect("Failed to create processor");
    
    // Create mock transaction results with successful execution
    let mut transaction_results = Vec::new();
    
    for i in 0..3 {
        let result = TransactionResult {
            transaction_hash: H256::from_low_u64_be(i),
            success: true,
            gas_used: 21000,
            state_changes: Vec::new(),
            proof: None, // Will be generated by generate_batch_proofs
            execution_time: Duration::from_millis(10),
            dependencies: Vec::new(),
            error: None,
        };
        
        transaction_results.push(result);
    }
    
    // Generate batch proofs with real ZODA
    let result = processor.generate_batch_proofs(transaction_results).await;
    
    assert!(result.is_ok(), "Batch proof generation should succeed");
    let results_with_proofs = result.unwrap();
    
    // Verify all transactions have proofs
    assert_eq!(results_with_proofs.len(), 3);
    
    for result in &results_with_proofs {
        assert!(result.proof.is_some(), "Each transaction should have a proof");
        let proof = result.proof.as_ref().unwrap();
        
        // Real ZODA proofs should be non-trivial (not just zeros)
        assert!(!proof.is_empty(), "Proof should not be empty");
        
        // For successful proof generation, the proof should contain actual data
        if result.success {
            // Check that it's not just a placeholder (all zeros)
            let is_placeholder = proof.iter().all(|&b| b == 0);
            // Real ZODA proofs should contain actual cryptographic data
            println!("Proof for transaction: {} bytes, is_placeholder: {}", proof.len(), is_placeholder);
        }
    }
    
    println!("✅ ZODA batch proof integration test passed!");
}

#[tokio::test]
async fn test_zoda_batch_proof_failure_handling() {
    // Test that failed proof generation is handled gracefully
    let config = BlockExecutionConfig::default();
    
    let processor = TransactionProcessor::new(config).await.expect("Failed to create processor");
    
    // Create transaction result that might cause proof generation failure
    let mut transaction_results = vec![TransactionResult {
        transaction_hash: H256::from_low_u64_be(1),
        success: true,
        gas_used: 21000,
        state_changes: Vec::new(),
        proof: None,
        execution_time: Duration::from_millis(10),
        dependencies: Vec::new(),
        error: None,
    }];
    
    // Generate batch proofs - should handle failures gracefully
    let result = processor.generate_batch_proofs(transaction_results).await;
    
    assert!(result.is_ok(), "Batch proof generation should not panic on failures");
    let results_with_proofs = result.unwrap();
    
    // Should still return results, possibly with fallback proofs
    assert_eq!(results_with_proofs.len(), 1);
    assert!(results_with_proofs[0].proof.is_some(), "Should have some proof even on failure");
    
    println!("✅ ZODA batch proof failure handling test passed!");
}

#[tokio::test]
async fn test_transaction_processor_has_pcd_adapter() {
    // Test that processor correctly initializes with PCD adapter
    let config = BlockExecutionConfig::default();
    
    let processor = TransactionProcessor::new(config).await;
    assert!(processor.is_ok(), "Processor creation should succeed");
    
    println!("✅ TransactionProcessor PCD adapter initialization test passed!");
}
